# -*- coding: utf-8 -*-
"""ProgEspec

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e22fL1L8Iv8dB-CnQmf99S9PUcGg0MAX
"""

!pip install experta==1.9.4 frozendict==1.2

import collections
import collections.abc

collections.Mapping = collections.abc.Mapping
collections.MutableMapping = collections.abc.MutableMapping
collections.Sequence = collections.abc.Sequence

from experta import Fact, KnowledgeEngine, AND, TEST, MATCH, Rule

class Finalidade(Fact):
    pass


class Orcamento(Fact):
    pass


class Desempenho(Fact):
    pass


class Armazenamento(Fact):
    pass


class Recomendacao(Fact):
    pass


class PCRecomend(KnowledgeEngine):

    @Rule(
        Orcamento(valor=MATCH.valor),
        TEST(lambda valor: valor < 3000)
    )
    def perfil_basico(self):
        self.declare(
            Recomendacao(perfil="basico")
        )

    @Rule(
        Orcamento(valor=MATCH.valor),
        TEST(lambda valor: 3000 <= valor < 6000)
    )
    def perfil_intermediario(self):
        self.declare(
            Recomendacao(perfil="intermediario")
        )

    @Rule(
        Orcamento(valor=MATCH.valor),
        TEST(lambda valor: valor >= 6000)
    )
    def perfil_avancado(self):
        self.declare(
            Recomendacao(perfil="avancado")
        )

    @Rule(
        Finalidade(tipo="jogos"),
        Desempenho(nivel="alto")
    )
    def jogos_alto(self):
        self.declare(
            Recomendacao(
                processador="Processador de alto desempenho",
                placa_video="Placa de vídeo dedicada de alto desempenho",
                ram="32 GB"
            )
        )

    @Rule(
        Finalidade(tipo="jogos"),
        Desempenho(nivel="intermediario")
    )
    def jogos_intermediario(self):
        self.declare(
            Recomendacao(
                processador="Processador intermediário",
                placa_video="Placa de vídeo dedicada intermediária",
                ram="16 GB"
            )
        )

    @Rule(
        Finalidade(tipo="jogos"),
        Desempenho(nivel="basico")
    )
    def jogos_basico(self):
        self.declare(
            Recomendacao(
                processador="Processador de entrada",
                placa_video="Placa de vídeo básica ou integrada",
                ram="8 GB"
            )
        )

    @Rule(
        Finalidade(tipo="estudos")
    )
    def estudos(self):
        self.declare(
            Recomendacao(
                processador="Processador de entrada",
                placa_video="Gráficos integrados",
                ram="8 GB"
            )
        )

    @Rule(
        Finalidade(tipo="programacao")
    )
    def programacao(self):
        self.declare(
            Recomendacao(
                processador="Processador intermediário",
                placa_video="Gráficos integrados",
                ram="16 GB"
            )
        )

    @Rule(
        Finalidade(tipo="edicao"),
        Desempenho(nivel="alto")
    )
    def edicao_alto(self):
        self.declare(
            Recomendacao(
                processador="Processador de alto desempenho",
                placa_video="Placa de vídeo dedicada",
                ram="32 GB"
            )
        )

    @Rule(
        Finalidade(tipo="edicao"),
        Desempenho(nivel="intermediario")
    )
    def edicao_intermediario(self):
        self.declare(
            Recomendacao(
                processador="Processador intermediário",
                placa_video="Placa de vídeo intermediária",
                ram="16 GB"
            )
        )

    @Rule(
        Finalidade(tipo="edicao"),
        Desempenho(nivel="basico")
    )
    def edicao_basico(self):
        self.declare(
            Recomendacao(
                processador="Processador de entrada",
                placa_video="Gráficos integrados",
                ram="8 GB"
            )
        )


def escolher(pergunta, opcoes):

    print("\n" + pergunta)

    for numero, opcao in enumerate(opcoes, 1):
        print(f"[{numero}] {opcao[0]}")

    while True:

        try:
            escolha = int(input("Escolha: "))

            if 1 <= escolha <= len(opcoes):
                return opcoes[escolha - 1][1]

        except ValueError:
            pass

        print("Opção inválida.")


ORCAMENTO_MINIMO = 2000


def obter_orcamento():

    while True:

        try:
            valor = float(
                input("\nDigite o orçamento total: R$ ")
            )

            if valor >= ORCAMENTO_MINIMO:
                return valor

            print(
                f"Orçamento insuficiente. O mínimo para montar "
                f"um computador é R$ {ORCAMENTO_MINIMO:.2f}."
            )
            continue

        except ValueError:
            pass

        print("Digite um valor válido.")


def confirmar_escolhas(orcamento, finalidade, desempenho, armazenamento):

    nomes_finalidade = {
        "jogos": "Jogos",
        "estudos": "Estudos",
        "programacao": "Programação",
        "edicao": "Edição de imagens e vídeos"
    }

    nomes_desempenho = {
        "basico": "Básico",
        "intermediario": "Intermediário",
        "alto": "Alto"
    }

    nomes_armazenamento = {
        "500gb": "500 GB",
        "1tb": "1 TB",
        "2tb": "2 TB"
    }

    print("\n" + "=" * 60)
    print("CONFIRME SUAS ESCOLHAS")
    print("=" * 60)
    print(f"Orçamento: R$ {orcamento:.2f}")
    print(f"Finalidade: {nomes_finalidade[finalidade]}")
    print(f"Desempenho: {nomes_desempenho[desempenho]}")
    print(f"Armazenamento: {nomes_armazenamento[armazenamento]}")
    print("=" * 60)

    return escolher(
        "Está tudo certo?",
        [
            ("Sim, continuar", True),
            ("Não, refazer orçamento", False)
        ]
    )


def obter_configuracao(recomendacao, armazenamento):

    processador = recomendacao["processador"]
    placa_video = recomendacao["placa_video"]
    ram = recomendacao["ram"]

    precos_processador = {
        "Processador de entrada": 650,
        "Processador intermediário": 950,
        "Processador de alto desempenho": 1800
    }

    precos_ram = {
        "8 GB": 180,
        "16 GB": 400,
        "32 GB": 750
    }

    precos_armazenamento = {
        "500gb": 280,
        "1tb": 550,
        "2tb": 950
    }

    precos_placa_mae = {
        "Processador de entrada": 400,
        "Processador intermediário": 600,
        "Processador de alto desempenho": 950
    }

    precos_fonte = {
        "Processador de entrada": 250,
        "Processador intermediário": 350,
        "Processador de alto desempenho": 500
    }

    precos_gabinete = {
        "Processador de entrada": 180,
        "Processador intermediário": 280,
        "Processador de alto desempenho": 400
    }

    texto_video = placa_video.lower()

    if "integrado" in texto_video or "integrada" in texto_video:
        preco_placa_video = 0

    elif "básica" in texto_video:
        preco_placa_video = 800

    elif "intermediária" in texto_video:
        preco_placa_video = 1500

    elif "alto desempenho" in texto_video:
        preco_placa_video = 2800

    elif "dedicada" in texto_video:
        preco_placa_video = 1800

    else:
        preco_placa_video = 0

    if preco_placa_video >= 2500:

        preco_fonte = 650

    elif preco_placa_video >= 1200:

        preco_fonte = 450

    else:

        preco_fonte = precos_fonte[processador]

    precos = {
        "Processador": precos_processador[processador],
        "Placa de vídeo": preco_placa_video,
        "Memória RAM": precos_ram[ram],
        "Armazenamento": precos_armazenamento[armazenamento],
        "Placa-mãe": precos_placa_mae[processador],
        "Fonte": preco_fonte,
        "Gabinete": precos_gabinete[processador]
    }

    return precos


print("==============================")
print("PC RECOMEND")
print("Sistema Especialista para Montagem de Computadores")
print("==============================")


while True:

    orcamento = obter_orcamento()

    finalidade = escolher(
        "Qual será a finalidade do computador?",
        [
            ("Jogos", "jogos"),
            ("Estudos", "estudos"),
            ("Programação", "programacao"),
            ("Edição de imagens e vídeos", "edicao")
        ]
    )

    desempenho = escolher(
        "Qual desempenho você deseja?",
        [
            ("Básico", "basico"),
            ("Intermediário", "intermediario"),
            ("Alto", "alto")
        ]
    )

    armazenamento = escolher(
        "Quanto armazenamento deseja?",
        [
            ("500 GB", "500gb"),
            ("1 TB", "1tb"),
            ("2 TB", "2tb")
        ]
    )

    if not confirmar_escolhas(orcamento, finalidade, desempenho, armazenamento):
        print("\nOk, vamos recomeçar.")
        continue

    engine = PCRecomend()

    engine.reset()

    engine.declare(Orcamento(valor=orcamento))
    engine.declare(Finalidade(tipo=finalidade))
    engine.declare(Desempenho(nivel=desempenho))
    engine.declare(Armazenamento(capacidade=armazenamento))

    engine.run()

    perfil = None
    recomendacao = None

    for fato in engine.facts.values():

        if isinstance(fato, Recomendacao):

            if fato.get("perfil") is not None:
                perfil = fato["perfil"]

            if fato.get("processador") is not None:
                recomendacao = fato

    if perfil is None or recomendacao is None:
        break

    precos = obter_configuracao(recomendacao, armazenamento)
    total = sum(precos.values())

    if total <= orcamento:
        break

    print(
        f"\nEssa configuração custa R$ {total:.2f}, "
        f"acima do seu orçamento de R$ {orcamento:.2f}."
    )
    print("Vamos recomeçar, com um orçamento maior ou opções mais baratas.")


if perfil is None or recomendacao is None:

    print("\nNão foi possível gerar uma configuração.")


else:

    print("\n" + "=" * 60)
    print("RECOMENDAÇÃO DO SISTEMA")
    print("=" * 60)

    print(f"Finalidade: {finalidade}")
    print(f"Desempenho: {desempenho}")
    print(f"Armazenamento: {armazenamento}")
    print(f"Orçamento disponível: R$ {orcamento:.2f}")

    print("\nComponentes recomendados:")

    print(f"Processador: {recomendacao['processador']}")
    print(f"Placa de vídeo: {recomendacao['placa_video']}")
    print(f"Memória RAM: {recomendacao['ram']}")
    print(f"Armazenamento: {armazenamento}")

    print("\nPreços estimados:")

    for componente, preco in precos.items():
        print(f"{componente}: R$ {preco:.2f}")

    print("\n" + "-" * 60)

    print(f"Total estimado: R$ {total:.2f}")
    print(f"Orçamento disponível: R$ {orcamento:.2f}")
    print("Status: Configuração dentro do orçamento.")

    print("=" * 60)
    print("Análise concluída.")
    print("=" * 60)

